apiVersion: backstage.io/v1alpha1
kind: API
metadata:
  name: track-service-grpc
  description: "gRPC API for tracks"
spec:
  type: grpc
  lifecycle: production
  owner: "group:default/content"
  definition:
    $text: ./src/main/proto/track.proto
---
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: track-service
  description: "gRPC service for tracks"
  tags:
    - java
    - grpc
  annotations:
    backstage.io/techdocs-ref: dir:.
    github.com/project-slug: spotify-portal-public-demo/track-service
    sonarqube.org/project-key: spotify-portal-public-demo_track-service
    grafana/dashboard-selector: track-service
    grafana/alert-label-selector: service_name=track-service
    backstage.io/kubernetes-id: track-service
    backstage.io/kubernetes-namespace: track-service
    backstage.io/kubernetes-label-selector: app=track-service
spec:
  type: service
  lifecycle: production
  owner: "group:default/content"
  system: "system:default/metadata"
  providesApis:
    - track-service-grpc
