apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: "track-service"
  description: "Service for everything related to tracks"
  annotations:
    backstage.io/techdocs-ref: dir:.
    github.com/project-slug: spotify-portal-public-demo/track-service
    sonarqube.org/project-key: spotify-portal-public-demo_track-service
spec:
  type: service
  lifecycle: experimental
  owner: "group:default/app-devs"
